import { Team } from "../model/interface";
export const BYE_WEEKS = [{
'1': [],
'2': [],
'3': [],
'4': [],
'5': ['8', '24', '21', '10'],
'6': ['12', '14', '15', '16'],
'7': ['3', '6'],
'8': [],
'9': ['23', '25'],
'10': ['5', '9', '13', '26'],
'11': ['22', '29', '19', '27'],
'12': ['1', '2', '4', '30', '18', '20'],
'13': [],
'14': ['33', '7', '34', '11', '17', '28'],
'15': [],
'16': [],
'17': [],
'18': []
}];

export const INITIALIZE_TEAMS = (inputTeams: Team[]) => {
  let tmpTeam: Team = {
    teamId: '1',
    teamName: 'Atlanta Falcons',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    pointsTotal: 0,
    pointsGivenTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '2',
    teamName: 'Buffalo Bills',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [],
    pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '3',
    teamName: 'Chicago Bears',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '4',
    teamName: 'Cincinnati Bengals',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '5',
    teamName: 'Cleveland Browns',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '6',
    teamName: 'Dallas Cowboys',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '7',
    teamName: 'Denver Broncos',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '8',
    teamName: 'Detroit Lions',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '9',
    teamName: 'Green Bay Packers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '10',
    teamName: 'Tennesse Titans',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '11',
    teamName: 'Indianapolis Colts',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '12',
    teamName: 'Kansas City Chiefs',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '13',
    teamName: 'Las Vegas Raiders',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '14',
    teamName: 'Los Angeles Rams',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '15',
    teamName: 'Miami Dolphins',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '16',
    teamName: 'Minnesota Vikings',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '17',
    teamName: 'New England Patriots',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '18',
    teamName: 'New Orleans Saints',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '19',
    teamName: 'New York Giants',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '20',
    teamName: 'New York Jets',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '21',
    teamName: 'Philadelphia Eagles',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '22',
    teamName: 'Arizona Cardinals',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '23',
    teamName: 'Pittsburgh Steelers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '24',
    teamName: 'Los Angeles Chargers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '25',
    teamName: 'San Francisco 49ers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '26',
    teamName: 'Seattle Seahawks',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '27',
    teamName: 'Tampa Bay Buccaneers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '28',
    teamName: 'Washington Commanders',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '29',
    teamName: 'Carolina Panthers',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '30',
    teamName: 'Jacksonville Jaguars',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '33',
    teamName: 'Baltimore Ravens',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  tmpTeam = {
    teamId: '34',
    teamName: 'Houston Texans',
    games: [],
    passingYardsTotal: 0,
    passingTdsTotal: 0,
    rushingYardsTotal: 0,
    rushingTdsTotal: 0,
    sacksTotal: 0,
    interceptionsTotal: 0,
    firstDownsTotal: 0,
    thirdDownPctTotal: [],
    redzoneScoringPctGivenTotal: [],
thirdDownPctAvg: 0,
redzoneScoringPctAvg: 0,
thirdDownConvPctGivenAvg: 0,
redzoneScoringPctGivenAvg: 0,
    pointsTotal: 0,
    passingAttemptsGivenTotal: 0,
    passingYardsGivenTotal: 0,
    passingTdsGivenTotal: 0,
    rushingAttemptsGivenTotal: 0,
    rushingYardsGivenTotal: 0,
    rushingTdsGivenTotal: 0,
    sacksGivenTotal: 0,
    interceptionsGivenTotal: 0,
    firstDownsGivenTotal: 0,
    thirdDownConvPctGivenTotal: [],
    passingAttemptsTotal: 0,
    rushingAttemptsTotal: 0,
    redzoneScoringPctTotal: [], pointsGivenTotal: 0,
  };
  inputTeams.push(tmpTeam);

  return inputTeams;
};


