export interface FilterStats {
  passAttempts: WinLoss;
  passYards: WinLoss;
  passTds: WinLoss;
  rushAttempts: WinLoss;
  rushYards: WinLoss;
  rushTds: WinLoss;
  firstDowns: WinLoss;
  interceptions: WinLoss;
  sacks: WinLoss;
  thirdDown: WinLoss;
  redzone: WinLoss;
  points: WinLoss;
}

export interface WinLoss {
  wins: number;
  winsArr: boolean[];
  winsArr2: boolean[];
  winsArr3: boolean[];
  winsArr4: boolean[];
  winsArr5: boolean[];
  losses: number;
}

export interface AggregateStats {
  turnoverDiffWins: number;
  turnoverDiffLosses: number;
  turnoverDiffAtsWins: number;
  turnoverDiffAtsLosses: number;
  combineDiffHighWins: number;
  combineDiffHighLosses: number;
  mlDiffWins: number;
  mlDiffLosses: number;
  mlHighWins: number;
  mlHighLosses: number;
  mlOppLowWins: number;
  mlOppLowLosses: number;
  combineAtsDiffHighWins: number;
  combineAtsDiffHighLosses: number;
  combineFavDiffHighWins: number;
  combineFavDiffHighLosses: number;
  combineUnderDiffHighWins: number;
  combineUnderDiffHighLosses: number;
  atsDiffWins: number;
  atsDiffLosses: number;
  atsHighWins: number;
  atsHighLosses: number;
  atsOppLowWins: number;
  atsOppLowLosses: number;
  favDiffWins: number,
  favDiffLosses: number,
  favHighWins: number,
  favHighLosses: number,
  favOppLowWins: number,
  favOppLowLosses: number,
  underDiffWins: number,
  underDiffLosses: number,
  underHighWins: number,
  underHighLosses: number,
  underOppLowWins: number,
  underOppLowLosses: number,
}


export interface Team {
  currentWeekWinLoss: string;
  currentWeekAts: string;
  netSpread: number;
  currentWeekPoints: number;
  currentWeekPointsAgainst: number;
  filterStats: FilterStats;
  filterAtsStats: FilterStats;
  filterAtsFavoritesStats: FilterStats;
  filterAtsUnderdogStats: FilterStats;
  nextGameDate: Date;
  nextGameSpread: string;
  nextGameDetails: string;
  teamInitials: string;
  isNextGameFavorite: boolean;
  nextOpponent: string;
  nextOpponentWins: number;
  nextOpponentLosses: number;
  nextOpponentAtsWins: number;
  nextOpponentAtsLosses: number;
  teamIndex: number;
  teamId: string;
  teamName: string;
  games: Game[]
  passingAttemptsTotal: number;
  passingYardsTotal: number;
  passingTdsTotal: number;
  rushingAttemptsTotal: number;
  rushingYardsTotal: number;
  rushingTdsTotal: number;
  sacksTotal: number;
  turnoverDiffTotal: number;
  interceptionsTotal: number;
  firstDownsTotal: number
  thirdDownPctTotal: number[];
  thirdDownPctAvg: number;
  redzoneScoringPctTotal: number[];
  redzoneScoringPctAvg: number;
  pointsTotal: number;
  pointsGivenTotal: number;
  passingAttemptsGivenTotal: number;
  passingYardsGivenTotal: number;
  passingTdsGivenTotal: number;
  rushingAttemptsGivenTotal: number;
  rushingYardsGivenTotal: number;
  rushingTdsGivenTotal: number;
  sacksGivenTotal: number;
  interceptionsGivenTotal: number;
  firstDownsGivenTotal: number
  thirdDownConvPctGivenTotal: number[];
  thirdDownConvPctGivenAvg: number;
  redzoneScoringPctGivenTotal: number[];
  redzoneScoringPctGivenAvg: number;
  wins: number;
  losses: number;
  atsWins: number;
  atsLosses: number;
  customAtsWins: number;
  customAtsLosses: number;
}

export interface Game {
  date: any;
  opponentId: string;
  homeOrAway: string;
  isFavorite?: boolean;
  gameId: number;
  points: number;
  turnoverDiff: number;
  passingAttempts: number;
  passingYards: number;
  passingTds: number;
  rushingAttempts: number;
  rushingYards: number;
  rushingTds: number;
  sacks: number;
  interceptions: number;
  firstDowns: number
  thirdDownConvPct: number;
  redzoneScoringPct: number;
  spread: number;
  pointsGiven: number;
  passingAttemptsGiven: number;
  passingYardsGiven: number;
  passingTdsGiven: number;
  rushingAttemptsGiven: number;
  rushingYardsGiven: number;
  rushingTdsGiven: number;
  sacksGiven: number;
  interceptionsGiven: number;
  firstDownsGiven: number
  thirdDownConvPctGiven: number;
  redzoneScoringPctGiven: number;
}
